# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TiHub_v.2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 415)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(30, 190, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(30, 240, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Stop.setFont(font)
        self.Stop.setObjectName("Stop")
        self.StateCollect = QtWidgets.QGroupBox(self.centralwidget)
        self.StateCollect.setGeometry(QtCore.QRect(20, 170, 101, 121))
        self.StateCollect.setObjectName("StateCollect")
        self.Savebuttop = QtWidgets.QGroupBox(self.centralwidget)
        self.Savebuttop.setGeometry(QtCore.QRect(20, 80, 101, 81))
        self.Savebuttop.setObjectName("Savebuttop")
        self.SavePath = QtWidgets.QToolButton(self.Savebuttop)
        self.SavePath.setGeometry(QtCore.QRect(10, 30, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.SavePath.setFont(font)
        self.SavePath.setObjectName("SavePath")
        self.File = QtWidgets.QGroupBox(self.centralwidget)
        self.File.setGeometry(QtCore.QRect(140, 170, 281, 121))
        self.File.setObjectName("File")
        self.State = QtWidgets.QTextBrowser(self.File)
        self.State.setGeometry(QtCore.QRect(10, 20, 261, 91))
        self.State.setObjectName("State")
        self.SetSampleFrequency = QtWidgets.QGroupBox(self.centralwidget)
        self.SetSampleFrequency.setGeometry(QtCore.QRect(20, 10, 261, 56))
        self.SetSampleFrequency.setObjectName("SetSampleFrequency")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SetSampleFrequency)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SamepleFrequency = QtWidgets.QLabel(self.SetSampleFrequency)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.SamepleFrequency.setFont(font)
        self.SamepleFrequency.setObjectName("SamepleFrequency")
        self.horizontalLayout.addWidget(self.SamepleFrequency)
        self.Rate = QtWidgets.QComboBox(self.SetSampleFrequency)
        self.Rate.setObjectName("Rate")
        self.horizontalLayout.addWidget(self.Rate)
        self.SetRegister = QtWidgets.QPushButton(self.SetSampleFrequency)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.SetRegister.setFont(font)
        self.SetRegister.setObjectName("SetRegister")
        self.horizontalLayout.addWidget(self.SetRegister)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 10, 81, 71))
        self.label.setObjectName("label")
        self.RealTimePlot = QtWidgets.QGroupBox(self.centralwidget)
        self.RealTimePlot.setGeometry(QtCore.QRect(20, 300, 101, 71))
        self.RealTimePlot.setObjectName("RealTimePlot")
        self.Plot = QtWidgets.QPushButton(self.RealTimePlot)
        self.Plot.setGeometry(QtCore.QRect(10, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Plot.setFont(font)
        self.Plot.setObjectName("Plot")
        self.LoadFile = QtWidgets.QGroupBox(self.centralwidget)
        self.LoadFile.setGeometry(QtCore.QRect(140, 300, 281, 71))
        self.LoadFile.setObjectName("LoadFile")
        self.Load = QtWidgets.QPushButton(self.LoadFile)
        self.Load.setGeometry(QtCore.QRect(10, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Load.setFont(font)
        self.Load.setObjectName("Load")
        self.LoadPlot = QtWidgets.QPushButton(self.LoadFile)
        self.LoadPlot.setGeometry(QtCore.QRect(70, 20, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.LoadPlot.setFont(font)
        self.LoadPlot.setObjectName("LoadPlot")
        self.LoadFilePath = QtWidgets.QTextBrowser(self.LoadFile)
        self.LoadFilePath.setGeometry(QtCore.QRect(130, 20, 141, 41))
        self.LoadFilePath.setObjectName("LoadFilePath")
        self.SaveFIlePath = QtWidgets.QTextBrowser(self.centralwidget)
        self.SaveFIlePath.setGeometry(QtCore.QRect(150, 110, 261, 41))
        self.SaveFIlePath.setObjectName("SaveFIlePath")
        self.SavePathDisplay = QtWidgets.QGroupBox(self.centralwidget)
        self.SavePathDisplay.setGeometry(QtCore.QRect(140, 80, 281, 80))
        self.SavePathDisplay.setObjectName("SavePathDisplay")
        self.SavePathDisplay.raise_()
        self.StateCollect.raise_()
        self.SetSampleFrequency.raise_()
        self.File.raise_()
        self.Savebuttop.raise_()
        self.Start.raise_()
        self.Stop.raise_()
        self.label.raise_()
        self.RealTimePlot.raise_()
        self.LoadFile.raise_()
        self.SaveFIlePath.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Start.setText(_translate("MainWindow", "Start"))
        self.Stop.setText(_translate("MainWindow", "Stop"))
        self.StateCollect.setTitle(_translate("MainWindow", "State Collect"))
        self.Savebuttop.setTitle(_translate("MainWindow", "Save"))
        self.SavePath.setText(_translate("MainWindow", "Save Path"))
        self.File.setTitle(_translate("MainWindow", "File Log"))
        self.SetSampleFrequency.setTitle(_translate("MainWindow", "Set Sample Frequency"))
        self.SamepleFrequency.setText(_translate("MainWindow", "Sameple_Frequency"))
        self.SetRegister.setText(_translate("MainWindow", "Set Register"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.RealTimePlot.setTitle(_translate("MainWindow", "Real Time Plot"))
        self.Plot.setText(_translate("MainWindow", "Plot"))
        self.LoadFile.setTitle(_translate("MainWindow", "Load File Plot"))
        self.Load.setText(_translate("MainWindow", "Load"))
        self.LoadPlot.setText(_translate("MainWindow", "Plot"))
        self.SavePathDisplay.setTitle(_translate("MainWindow", "Save Path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

